### ISSUE TITLE
Spring Boot 3.0 requires Java 17 or later

### ISSUE THREAD

**Issue by reimer-atb** [eclipse-researchlabs/smartclide-api-gateway#13]
See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#review-system-requirements

The pom has been updated to spring boot 3.0 but the Dockerfile and github workflows still use Java 16 and 11, respectively. That's why builds are failing: https://github.com/eclipse-opensmartclide/smartclide-api-gateway/actions/runs/3547566492/jobs/5957825910.

Migration to spring boot 3.0 also requires additional work besides updating the version number in most cases: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide

**Comment by deanone** [comment]
@philipreimer thanks mate I'll check it.

**Comment by deanone** [comment]
I close the issue since it should have been resolved now after merging PR #20 .
